services:
    SemiGUIDB:
        image: mysql:8.0
        container_name: SemiGUI_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: SemiGuiData
            TZ: Asia/Seoul
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci